# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state/ssl_gc_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19state/ssl_gc_common.proto\x12\x05sslgc\"0\n\x07RobotId\x12\n\n\x02id\x18\x01 \x01(\r\x12\x19\n\x04team\x18\x02 \x01(\x0e\x32\x0b.sslgc.Team*)\n\x04Team\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x08\n\x04\x42LUE\x10\x02*1\n\x08\x44ivision\x12\x0f\n\x0b\x44IV_UNKNOWN\x10\x00\x12\t\n\x05\x44IV_A\x10\x01\x12\t\n\x05\x44IV_B\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state.ssl_gc_common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEAM._serialized_start=86
  _TEAM._serialized_end=127
  _DIVISION._serialized_start=129
  _DIVISION._serialized_end=178
  _ROBOTID._serialized_start=36
  _ROBOTID._serialized_end=84
# @@protoc_insertion_point(module_scope)
